### ISSUE TITLE
Compléter les pages relatives à /projects

### ISSUE THREAD

**Issue by JudithLco** [Melomania-be/front#12]
Page /projects
- [x] Les boutons ne fonctionnent pas :  See all projects ; See current projects ; See passed projects
- [x] Cliquer sur un projet ne renvoie pas à /projects/:id

--------------------------------------
Page /projects/create
- [x] Récupération de "pieces" non fonctionnel
- [x] La création de "content_registration" n'a pas été faite
- [x] Les données ne sont pas envoyées au back

-------------------------------------
Page /projects/:id
- [x] Dashboard d'un projet
- [x] Modification d'un projet
- [x] #19
- [x] #20
- [x] création d'une callsheet #20
- [x] modification d'une callsheet #20
- [x] ajout d'une callsheet #20
- [x] création et modification de la page registration #20
- [x] Liste de participant
- [x] Amélioration du visuel de la liste des participants
- [x] Création d'un participant
- [x] Modification D'un participant
- [x] Validation D'un participant
- [x] #26
- [x] Project linked to a folder

**Comment by melian-e** [comment]
-  [ ] Dashboard d'un projet
-  [ ] Modification d'un projet
-  [ ] Gestion des mails d'un projet
-  [ ] liste des callsheets
-  [ ] création d'une callsheet
-  [ ] modification d'une callsheet
-  [ ] ajout d'une callsheet
-  [ ] création et modification de la page registration
-  [ ] Liste de participant
-  [ ] Amélioration du visuel de la liste des participants
-  [ ] Création d'un participant
-  [ ] Modification D'un participant
-  [ ] Validation D'un participant
-  [ ] Attendance : planning permettant de visualiser la présence des différents participants aux concerts et répétitions
